baseurl         = "https://datasingularity.org"
theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"

[params]
  title       = "Digital Codex"
  subtitle    = "\"You cannot open a book without learning something.\"- Confucius"

  cover       = "HomeCover.jpeg"
  description = "Learn * Think * Design * Code"
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = "agnurva"
  githubName = "agnurva"
  linkedinName = "clement-francis-3407aa8b"

  logo = ""
  orgName = "Data Singularity"
  orgWebsite = "https://datasingularity.org"
  orgDescription = "A collection of ideas to achieve Data Singularity"

  author = "Clement Francis"
  authorAvatar = "img/ghost-icon.png"
  authorLocation = "Bengaluru, India"
  authorWebsite = "https://datasingularity.org"
  authorDescription = "Data Analytics and Visualization Enthusiast"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/post/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Data Blogs"
  url = "/tags/Data"
  weight = 99

[[menu.main]]
  name = "Categories"
  url = "/categories/"
  weight = 95
